In [1]:
import pandas as pd
import numpy as np
import os

In [4]:
path="input_data/retagged_data/revised_subset_full_plates_some_neutralization_2026-08-10_RETAGGED_2026_08_17.csv"
df = pd.read_csv(path)

In [7]:
wide = df.pivot(
    index=['run_id','plate_row'],
    columns='plate_col',
    values='rlu'
)

In [8]:
wide

plate_col            1        2        3        4        5        6        7   \
run_id plate_row
75     1          476.0  10294.0   9174.0   9994.0   9826.0   8692.0  10480.0
       2          506.0  11198.0  13782.0  12470.0  10274.0  13380.0  13258.0
       3          530.0  11944.0  12730.0  13558.0   8880.0   8136.0  16339.0
       4          516.0  13524.0  12668.0  12398.0   3258.0   3106.0  16439.0
       5          544.0  13024.0   5898.0   5708.0   1754.0   1780.0  14116.0
...                 ...      ...      ...      ...      ...      ...      ...
1260   4          580.0  47115.0  14579.0  13458.0   2370.0   2518.0    570.0
       5          564.0  43457.0   2122.0   1668.0    648.0    634.0    526.0
       6          508.0  43107.0    498.0    526.0    632.0    518.0    528.0
       7          466.0  44409.0    458.0    482.0    538.0    488.0    462.0
       8          444.0  35512.0    484.0    570.0    494.0    530.0    518.0

plate_col              8        9        10       11       12
run_id plate_row
75     1          10458.0   9810.0   9492.0  11442.0  10454.0
       2          12990.0  14515.0  15953.0  13046.0  10998.0
       3          16171.0  14010.0  16247.0  11394.0   9204.0
       4          15275.0  15117.0  12740.0   7362.0   4926.0
       5          14237.0  12188.0  11350.0   2518.0   1482.0
...                   ...      ...      ...      ...      ...
1260   4            526.0  19775.0  16665.0   1804.0   1822.0
       5            496.0   2028.0   1606.0    508.0    512.0
       6            496.0    514.0    480.0    460.0    458.0
       7            472.0    518.0    440.0    450.0    414.0
       8            502.0    494.0    500.0    542.0    436.0

[264 rows x 12 columns]

In [20]:
vcs = df.loc[df.specrole=='vc']
ccs = df.loc[df.specrole=='cc']

vcs = vcs.pivot(
    index='run_id',
    columns='plate_row',
    values='rlu'
)

vcs.columns = [f"vc_{i}" for i in vcs.columns]

ccs = ccs.pivot(
    index='run_id',
    columns='plate_row',
    values='rlu'
)

ccs.columns = [f"cc_{i}" for i in ccs.columns]

In [23]:
samples = df.loc[df.specrole=='sample']
samples = samples.merge(vcs.reset_index(), on='run_id')
samples = samples.merge(ccs.reset_index(), on='run_id')

In [24]:
samples.shape

(2640, 44)

In [25]:
pd.options.display.max_columns=50

In [26]:
samples.head()

,run_id,run_name,plate_row,plate_col,rlu,min_diff,specrole,run,virus_name,concentration,monolix_id,rlu_max,rlu_min,rlu_norm,virus_col,mab,mablot,mab_virus,goes_down,virus_cc,id_unique,monolix_id_update,id_unique_update,mean_vc,mean_cc,binary_vc,binary_cc,binary_sample,vc_1,vc_2,vc_3,vc_4,vc_5,vc_6,vc_7,vc_8,cc_1,cc_2,cc_3,cc_4,cc_5,cc_6,cc_7,cc_8
0,411,290,1,4,53482.0,7.275958e-12,sample,9,6.0,0.045725,9|411|sample|4|274,62361.0,778.0,0.855821,274,70.0,8.0,70.0|274,True,1,411|290|274|70.0|8.0|0.045724737082761785,9|411|9|411|sample|4|274|4|274|70.0,411|290|274|70.0|8.0|0.045724737082761785,57906.875,910.0,0,0,1,57888.0,57026.0,62361.0,58423.0,61789.0,57424.0,54022.0,54322.0,868.0,912.0,846.0,900.0,962.0,886.0,922.0,984.0
1,411,290,2,3,40956.0,0.000000e+00,sample,9,6.0,0.137174,9|411|sample|3|274,62361.0,778.0,0.652420,274,70.0,8.0,70.0|274,True,1,411|290|274|70.0|8.0|0.13717421124828535,9|411|9|411|sample|3|274|3|274|70.0,411|290|274|70.0|8.0|0.13717421124828535,57906.875,910.0,0,0,1,57888.0,57026.0,62361.0,58423.0,61789.0,57424.0,54022.0,54322.0,868.0,912.0,846.0,900.0,962.0,886.0,922.0,984.0
2,411,290,3,3,25675.0,0.000000e+00,sample,9,6.0,0.411523,9|411|sample|3|274,62361.0,778.0,0.404284,274,70.0,8.0,70.0|274,True,1,411|290|274|70.0|8.0|0.41152263374485604,9|411|9|411|sample|3|274|3|274|70.0,411|290|274|70.0|8.0|0.41152263374485604,57906.875,910.0,0,0,1,57888.0,57026.0,62361.0,58423.0,61789.0,57424.0,54022.0,54322.0,868.0,912.0,846.0,900.0,962.0,886.0,922.0,984.0
3,411,290,4,3,7926.0,9.094947e-13,sample,9,6.0,1.234568,9|411|sample|3|274,62361.0,778.0,0.116071,274,70.0,8.0,70.0|274,True,1,411|290|274|70.0|8.0|1.234567901234568,9|411|9|411|sample|3|274|3|274|70.0,411|290|274|70.0|8.0|1.234567901234568,57906.875,910.0,0,0,1,57888.0,57026.0,62361.0,58423.0,61789.0,57424.0,54022.0,54322.0,868.0,912.0,846.0,900.0,962.0,886.0,922.0,984.0
4,411,290,5,3,2156.0,0.000000e+00,sample,9,6.0,3.703704,9|411|sample|3|274,62361.0,778.0,0.022376,274,70.0,8.0,70.0|274,True,1,411|290|274|70.0|8.0|3.703703703703704,9|411|9|411|sample|3|274|3|274|70.0,411|290|274|70.0|8.0|3.703703703703704,57906.875,910.0,0,0,1,57888.0,57026.0,62361.0,58423.0,61789.0,57424.0,54022.0,54322.0,868.0,912.0,846.0,900.0,962.0,886.0,922.0,984.0

In [27]:
samples.goes_down.value_counts()

goes_down
True     2592
False      48
Name: count, dtype: int64

In [28]:
savecols = [
    'run_id',
    'plate_row',
    'plate_col',
    'rlu',
    'run',
    'concentration',
    'monolix_id_update',
    'virus_col',
    'mab',
    'mab_virus',
    'goes_down',
]
savecols += vcs.columns.tolist() + ccs.columns.tolist()

In [34]:
samples[savecols].to_csv(
    'input_data/retagged_data/revised_subset_full_plates_some_neutralization_2026-08-10_RETAGGED_2026_08_17_rotated_20260822.csv',
    index=False
)

In [35]:
## this time try giving vc/cc concentraitons that increase slightly so that can model them as time

In [36]:
df2 = df.copy()

In [37]:
df2.head()

,run_id,run_name,plate_row,plate_col,rlu,min_diff,specrole,run,virus_name,concentration,monolix_id,rlu_max,rlu_min,rlu_norm,virus_col,mab,mablot,mab_virus,goes_down,virus_cc,id_unique,monolix_id_update,id_unique_update,mean_vc,mean_cc,binary_vc,binary_cc,binary_sample
0,411,290,1,4,53482.0,7.275958e-12,sample,9,6.0,0.045725,9|411|sample|4|274,62361.0,778.0,0.855821,274,70.0,8.0,70.0|274,True,1,411|290|274|70.0|8.0|0.045724737082761785,9|411|9|411|sample|4|274|4|274|70.0,411|290|274|70.0|8.0|0.045724737082761785,57906.875,910.0,0,0,1
1,411,290,2,3,40956.0,0.000000e+00,sample,9,6.0,0.137174,9|411|sample|3|274,62361.0,778.0,0.652420,274,70.0,8.0,70.0|274,True,1,411|290|274|70.0|8.0|0.13717421124828535,9|411|9|411|sample|3|274|3|274|70.0,411|290|274|70.0|8.0|0.13717421124828535,57906.875,910.0,0,0,1
2,411,290,3,3,25675.0,0.000000e+00,sample,9,6.0,0.411523,9|411|sample|3|274,62361.0,778.0,0.404284,274,70.0,8.0,70.0|274,True,1,411|290|274|70.0|8.0|0.41152263374485604,9|411|9|411|sample|3|274|3|274|70.0,411|290|274|70.0|8.0|0.41152263374485604,57906.875,910.0,0,0,1
3,411,290,4,3,7926.0,9.094947e-13,sample,9,6.0,1.234568,9|411|sample|3|274,62361.0,778.0,0.116071,274,70.0,8.0,70.0|274,True,1,411|290|274|70.0|8.0|1.234567901234568,9|411|9|411|sample|3|274|3|274|70.0,411|290|274|70.0|8.0|1.234567901234568,57906.875,910.0,0,0,1
4,411,290,5,3,2156.0,0.000000e+00,sample,9,6.0,3.703704,9|411|sample|3|274,62361.0,778.0,0.022376,274,70.0,8.0,70.0|274,True,1,411|290|274|70.0|8.0|3.703703703703704,9|411|9|411|sample|3|274|3|274|70.0,411|290|274|70.0|8.0|3.703703703703704,57906.875,910.0,0,0,1

In [39]:
df2.loc[df2.specrole=='vc', 'concentration'] = df2.loc[df2.specrole=='vc', 'plate_row'].astype(float)

In [40]:
df2.loc[df2.specrole=='vc']

,run_id,run_name,plate_row,plate_col,rlu,min_diff,specrole,run,virus_name,concentration,monolix_id,rlu_max,rlu_min,rlu_norm,virus_col,mab,mablot,mab_virus,goes_down,virus_cc,id_unique,monolix_id_update,id_unique_update,mean_vc,mean_cc,binary_vc,binary_cc,binary_sample
88,411,290,1,2,57888.0,NaN,vc,9,6.0,1.0,9|411|vc|1|2|274,62361.0,778.0,0.927366,274,69.0,0.0,69.0|274,False,1,NaN,9|411|9|411|vc|1|2|274|2|274|69.0,411|290|274|69.0|0.0|nan,57906.875,910.00,1,0,0
89,411,290,2,2,57026.0,NaN,vc,9,6.0,2.0,9|411|vc|2|2|274,62361.0,778.0,0.913369,274,69.0,0.0,69.0|274,False,1,NaN,9|411|9|411|vc|2|2|274|2|274|69.0,411|290|274|69.0|0.0|nan,57906.875,910.00,1,0,0
90,411,290,3,2,62361.0,NaN,vc,9,6.0,3.0,9|411|vc|3|2|274,62361.0,778.0,1.000000,274,69.0,0.0,69.0|274,False,1,NaN,9|411|9|411|vc|3|2|274|2|274|69.0,411|290|274|69.0|0.0|nan,57906.875,910.00,1,0,0
91,411,290,4,2,58423.0,NaN,vc,9,6.0,4.0,9|411|vc|4|2|274,62361.0,778.0,0.936054,274,69.0,0.0,69.0|274,False,1,NaN,9|411|9|411|vc|4|2|274|2|274|69.0,411|290|274|69.0|0.0|nan,57906.875,910.00,1,0,0
92,411,290,5,2,61789.0,NaN,vc,9,6.0,5.0,9|411|vc|5|2|274,62361.0,778.0,0.990712,274,69.0,0.0,69.0|274,False,1,NaN,9|411|9|411|vc|5|2|274|2|274|69.0,411|290|274|69.0|0.0|nan,57906.875,910.00,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3163,1260,617,4,2,47115.0,NaN,vc,8,23.0,4.0,8|1260|vc|4|2|319,47115.0,414.0,1.000000,319,69.0,0.0,69.0|319,False,1,NaN,8|1260|8|1260|vc|4|2|319|2|319|69.0,1260|617|319|69.0|0.0|nan,42984.625,528.25,1,0,0
3164,1260,617,5,2,43457.0,NaN,vc,8,23.0,5.0,8|1260|vc|5|2|319,47115.0,414.0,0.921672,319,69.0,0.0,69.0|319,False,1,NaN,8|1260|8|1260|vc|5|2|319|2|319|69.0,1260|617|319|69.0|0.0|nan,42984.625,528.25,1,0,0
3165,1260,617,6,2,43107.0,NaN,vc,8,23.0,6.0,8|1260|vc|6|2|319,47115.0,414.0,0.914177,319,69.0,0.0,69.0|319,False,1,NaN,8|1260|8|1260|vc|6|2|319|2|319|69.0,1260|617|319|69.0|0.0|nan,42984.625,528.25,1,0,0
3166,1260,617,7,2,44409.0,NaN,vc,8,23.0,7.0,8|1260|vc|7|2|319,47115.0,414.0,0.942057,319,69.0,0.0,69.0|319,False,1,NaN,8|1260|8|1260|vc|7|2|319|2|319|69.0,1260|617|319|69.0|0.0|nan,42984.625,528.25,1,0,0
3167,1260,617,8,2,35512.0,NaN,vc,8,23.0,8.0,8|1260|vc|8|2|319,47115.0,414.0,0.751547,319,69.0,0.0,69.0|319,False,1,NaN,8|1260|8|1260|vc|8|2|319|2|319|69.0,1260|617|319|69.0|0.0|nan,42984.625,528.25,1,0,0

In [38]:
df.loc[df.specrole=='vc']

,run_id,run_name,plate_row,plate_col,rlu,min_diff,specrole,run,virus_name,concentration,monolix_id,rlu_max,rlu_min,rlu_norm,virus_col,mab,mablot,mab_virus,goes_down,virus_cc,id_unique,monolix_id_update,id_unique_update,mean_vc,mean_cc,binary_vc,binary_cc,binary_sample
88,411,290,1,2,57888.0,NaN,vc,9,6.0,0.0,9|411|vc|1|2|274,62361.0,778.0,0.927366,274,69.0,0.0,69.0|274,False,1,NaN,9|411|9|411|vc|1|2|274|2|274|69.0,411|290|274|69.0|0.0|nan,57906.875,910.00,1,0,0
89,411,290,2,2,57026.0,NaN,vc,9,6.0,0.0,9|411|vc|2|2|274,62361.0,778.0,0.913369,274,69.0,0.0,69.0|274,False,1,NaN,9|411|9|411|vc|2|2|274|2|274|69.0,411|290|274|69.0|0.0|nan,57906.875,910.00,1,0,0
90,411,290,3,2,62361.0,NaN,vc,9,6.0,0.0,9|411|vc|3|2|274,62361.0,778.0,1.000000,274,69.0,0.0,69.0|274,False,1,NaN,9|411|9|411|vc|3|2|274|2|274|69.0,411|290|274|69.0|0.0|nan,57906.875,910.00,1,0,0
91,411,290,4,2,58423.0,NaN,vc,9,6.0,0.0,9|411|vc|4|2|274,62361.0,778.0,0.936054,274,69.0,0.0,69.0|274,False,1,NaN,9|411|9|411|vc|4|2|274|2|274|69.0,411|290|274|69.0|0.0|nan,57906.875,910.00,1,0,0
92,411,290,5,2,61789.0,NaN,vc,9,6.0,0.0,9|411|vc|5|2|274,62361.0,778.0,0.990712,274,69.0,0.0,69.0|274,False,1,NaN,9|411|9|411|vc|5|2|274|2|274|69.0,411|290|274|69.0|0.0|nan,57906.875,910.00,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3163,1260,617,4,2,47115.0,NaN,vc,8,23.0,0.0,8|1260|vc|4|2|319,47115.0,414.0,1.000000,319,69.0,0.0,69.0|319,False,1,NaN,8|1260|8|1260|vc|4|2|319|2|319|69.0,1260|617|319|69.0|0.0|nan,42984.625,528.25,1,0,0
3164,1260,617,5,2,43457.0,NaN,vc,8,23.0,0.0,8|1260|vc|5|2|319,47115.0,414.0,0.921672,319,69.0,0.0,69.0|319,False,1,NaN,8|1260|8|1260|vc|5|2|319|2|319|69.0,1260|617|319|69.0|0.0|nan,42984.625,528.25,1,0,0
3165,1260,617,6,2,43107.0,NaN,vc,8,23.0,0.0,8|1260|vc|6|2|319,47115.0,414.0,0.914177,319,69.0,0.0,69.0|319,False,1,NaN,8|1260|8|1260|vc|6|2|319|2|319|69.0,1260|617|319|69.0|0.0|nan,42984.625,528.25,1,0,0
3166,1260,617,7,2,44409.0,NaN,vc,8,23.0,0.0,8|1260|vc|7|2|319,47115.0,414.0,0.942057,319,69.0,0.0,69.0|319,False,1,NaN,8|1260|8|1260|vc|7|2|319|2|319|69.0,1260|617|319|69.0|0.0|nan,42984.625,528.25,1,0,0
3167,1260,617,8,2,35512.0,NaN,vc,8,23.0,0.0,8|1260|vc|8|2|319,47115.0,414.0,0.751547,319,69.0,0.0,69.0|319,False,1,NaN,8|1260|8|1260|vc|8|2|319|2|319|69.0,1260|617|319|69.0|0.0|nan,42984.625,528.25,1,0,0